
services:
  - type: web
    name: handy-strapi-dock
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npx serve -s dist
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 1337

