
services:
  - type: web
    name: handy-strapi-dock
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx strapi start
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 1337
      - key: HOST
        value: 0.0.0.0        

